name: AeonLW Wallet Build
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [osx-latest, windows-10, ubuntu-latest]

        steps:
            - name: Checkout git repo
              uses: actions/checkout@v1
            
            - name: move
              run: cd aeonlw
            
            - name: mkbin
              run: mkdir bin

            - name: Install node
              uses: actions/setup-node@v1
              with:
                node-version: "11.9.0"

            - name: Download Aeon binaries
              run: node ./build/download-binaries.js

            - name: Extract zip binaries
              if: runner.os != 'Linux'
              run: unzip latest.zip
              shell: bash
              working-directory: ./downloads

            - name: Extract gz binaries
              if: runner.os == 'Linux'
              run: tar -xf latest.bz2
              shell: bash
              working-directory: ./downloads

            - name: Move aeond binaries
              run: |
                find ./downloads -type f -name "aeond*" -exec cp '{}' ./bin \;
                find ./downloads -type f -name "aeond-wallet-rpc*" -exec cp '{}' ./bin \;
              shell: bash

            - name: Verify binaries
              run: ls ./bin
              shell: bash
            
            - name: Install builder
              run: npm install -g quasar-cli
              
            - name: Install npm deps  
              run: npm install -f

            - name: Publish window and linux binaries
              if: runner.os != 'macOS'
              run: npm run build
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Remove un-needed artifacts
              run: rm -r -- ./*/
              shell: bash
              working-directory: ./dist/electron-mat/Packaged

            - name: Upload artifacts
              uses: actions/upload-artifact@v1
              with:
                name: ${{ runner.OS }}
                path: dist/electron-mat/Packaged
